{"id":"31365251474","type":"IssuesEvent","actor":{"id":271906,"login":"yurivict","display_login":"yurivict","gravatar_id":"","url":"https://api.github.com/users/yurivict","avatar_url":"https://avatars.githubusercontent.com/u/271906?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"opened","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534","id":1866340188,"node_id":"I_kwDOA-eq3c5vPhdc","number":1534,"title":"Tests fail: cannot import name 'Config' from 'pytest'","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2023-08-25T05:46:02Z","updated_at":"2023-08-25T05:46:02Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n```\r\n[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.9/site-packages/pytest.py\", line 102, in <module>\r\n    raise SystemExit(pytest.main())\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 65, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 213, in _prepareconfig\r\n    return pluginmanager.hook.pytest_cmdline_parse(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 84, in <lambda>\r\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n    gen.send(outcome)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py\", line 94, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 80, in get_result\r\n    raise ex[1].with_traceback(ex[2])\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 789, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 997, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 943, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/local/lib/python3.9/importlib/metadata.py\", line 86, in load\r\n    module = import_module(match.group('module'))\r\n  File \"/usr/local/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py\", line 304, in load_module\r\n    exec(co, mod.__dict__)\r\n  File \"/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py\", line 6, in <module>\r\n    from pytest import Config, Parser\r\nImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)\r\nFAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests \r\ncd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nninja: build stopped: subcommand failed.\r\n*** Error code 1\r\n```\r\n\r\n**To Reproduce**\r\nRegular build and test with the ```run_tests``` target.\r\n\r\n**Environment (please complete the following information):**\r\n - OS: FreeBSD 13.2\r\n - Compiler version used clang-16\r\n - Build variables used n/a\r\n - liboqs version rev.914764c9\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/timeline","performed_via_github_app":null,"state_reason":null}},"public":true,"created_at":"2023-08-25T05:46:03Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31365965343","type":"IssuesEvent","actor":{"id":271906,"login":"yurivict","display_login":"yurivict","gravatar_id":"","url":"https://api.github.com/users/yurivict","avatar_url":"https://avatars.githubusercontent.com/u/271906?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"closed","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534","id":1866340188,"node_id":"I_kwDOA-eq3c5vPhdc","number":1534,"title":"Tests fail: cannot import name 'Config' from 'pytest'","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2023-08-25T05:46:02Z","updated_at":"2023-08-25T06:28:22Z","closed_at":"2023-08-25T06:28:21Z","author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n```\r\n[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.9/site-packages/pytest.py\", line 102, in <module>\r\n    raise SystemExit(pytest.main())\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 65, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 213, in _prepareconfig\r\n    return pluginmanager.hook.pytest_cmdline_parse(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 84, in <lambda>\r\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n    gen.send(outcome)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py\", line 94, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 80, in get_result\r\n    raise ex[1].with_traceback(ex[2])\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 789, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 997, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 943, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/local/lib/python3.9/importlib/metadata.py\", line 86, in load\r\n    module = import_module(match.group('module'))\r\n  File \"/usr/local/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py\", line 304, in load_module\r\n    exec(co, mod.__dict__)\r\n  File \"/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py\", line 6, in <module>\r\n    from pytest import Config, Parser\r\nImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)\r\nFAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests \r\ncd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nninja: build stopped: subcommand failed.\r\n*** Error code 1\r\n```\r\n\r\n**To Reproduce**\r\nRegular build and test with the ```run_tests``` target.\r\n\r\n**Environment (please complete the following information):**\r\n - OS: FreeBSD 13.2\r\n - Compiler version used clang-16\r\n - Build variables used n/a\r\n - liboqs version rev.914764c9\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/timeline","performed_via_github_app":null,"state_reason":"not_planned"}},"public":true,"created_at":"2023-08-25T06:28:22Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31377494018","type":"IssuesEvent","actor":{"id":69469731,"login":"marcbrevoort-cyberhive","display_login":"marcbrevoort-cyberhive","gravatar_id":"","url":"https://api.github.com/users/marcbrevoort-cyberhive","avatar_url":"https://avatars.githubusercontent.com/u/69469731?"},"repo":{"id":334511511,"name":"open-quantum-safe/oqs-provider","url":"https://api.github.com/repos/open-quantum-safe/oqs-provider"},"payload":{"action":"opened","issue":{"url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236","repository_url":"https://api.github.com/repos/open-quantum-safe/oqs-provider","labels_url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236/comments","events_url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236/events","html_url":"https://github.com/open-quantum-safe/oqs-provider/issues/236","id":1867177561,"node_id":"I_kwDOE_A9l85vSt5Z","number":236,"title":"What might impact content of oqsprov.c / oqsprov_capabilities.c ?","user":{"login":"marcbrevoort-cyberhive","id":69469731,"node_id":"MDQ6VXNlcjY5NDY5NzMx","avatar_url":"https://avatars.githubusercontent.com/u/69469731?v=4","gravatar_id":"","url":"https://api.github.com/users/marcbrevoort-cyberhive","html_url":"https://github.com/marcbrevoort-cyberhive","followers_url":"https://api.github.com/users/marcbrevoort-cyberhive/followers","following_url":"https://api.github.com/users/marcbrevoort-cyberhive/following{/other_user}","gists_url":"https://api.github.com/users/marcbrevoort-cyberhive/gists{/gist_id}","starred_url":"https://api.github.com/users/marcbrevoort-cyberhive/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/marcbrevoort-cyberhive/subscriptions","organizations_url":"https://api.github.com/users/marcbrevoort-cyberhive/orgs","repos_url":"https://api.github.com/users/marcbrevoort-cyberhive/repos","events_url":"https://api.github.com/users/marcbrevoort-cyberhive/events{/privacy}","received_events_url":"https://api.github.com/users/marcbrevoort-cyberhive/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2023-08-25T14:39:25Z","updated_at":"2023-08-25T14:39:25Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I have two oqsprovider builds created with the same build script on different systems.\r\nOn these two systems, `liboqs.a` is bit-identical.\r\nOpenSSL is built from the same commit; `libssl.a` is bit-identical between the systems,  `nm` on libcrypto.a reports \r\n ```\r\n 19268c19268\r\n< 0000000000000230 r list_sep.0\r\n---\r\n> 000000000000024c r list_sep.0\r\n```\r\nThe build of `oqsprovider.a` differs substantially between the two systems (despite the identical build scripts) with the main difference being in the object files generated from `oqsprov.c` / `oqsprov_capabilities.c`. What might impact the content of these files?\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/oqs-provider/issues/236/timeline","performed_via_github_app":null,"state_reason":null}},"public":true,"created_at":"2023-08-25T14:39:26Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
