{"id":"20715887035","type":"IssuesEvent","actor":{"id":36664211,"login":"vt-alt","display_login":"vt-alt","gravatar_id":"","url":"https://api.github.com/users/vt-alt","avatar_url":"https://avatars.githubusercontent.com/u/36664211?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"opened","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1195","id":1167336068,"node_id":"I_kwDOA-eq3c5FlCKE","number":1195,"title":"ERROR tests/test_code_conventions.py::test_datasheet_yamllint ","user":{"login":"vt-alt","id":36664211,"node_id":"MDQ6VXNlcjM2NjY0MjEx","avatar_url":"https://avatars.githubusercontent.com/u/36664211?v=4","gravatar_id":"","url":"https://api.github.com/users/vt-alt","html_url":"https://github.com/vt-alt","followers_url":"https://api.github.com/users/vt-alt/followers","following_url":"https://api.github.com/users/vt-alt/following{/other_user}","gists_url":"https://api.github.com/users/vt-alt/gists{/gist_id}","starred_url":"https://api.github.com/users/vt-alt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vt-alt/subscriptions","organizations_url":"https://api.github.com/users/vt-alt/orgs","repos_url":"https://api.github.com/users/vt-alt/repos","events_url":"https://api.github.com/users/vt-alt/events{/privacy}","received_events_url":"https://api.github.com/users/vt-alt/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-12T16:40:40Z","updated_at":"2022-03-12T16:40:40Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"There appeared pytest error:\r\n```\r\n============================= test session starts ==============================\r\nplatform linux -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3\r\ncachedir: .pytest_cache\r\nrootdir: /usr/src/RPM/BUILD/liboqs-0.7.1\r\nplugins: xdist-2.5.0, forked-1.4.0\r\ngw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I\r\n...\r\n==================================== ERRORS ====================================\r\n__________________ ERROR at setup of test_datasheet_yamllint ___________________\r\n[gw3] linux -- Python 3.10.2 /usr/bin/python3\r\n\r\ncls = <class '_pytest.runner.CallInfo'>\r\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f6115e98c10>\r\nwhen = 'setup'\r\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\r\n\r\n    @classmethod\r\n    def from_call(\r\n        cls,\r\n        func: \"Callable[[], TResult]\",\r\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\r\n        reraise: Optional[\r\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\r\n        ] = None,\r\n    ) -> \"CallInfo[TResult]\":\r\n        \"\"\"Call func, wrapping the result in a CallInfo.\r\n    \r\n        :param func:\r\n            The function to call. Called without arguments.\r\n        :param when:\r\n            The phase in which the function is called.\r\n        :param reraise:\r\n            Exception or exceptions that shall propagate if raised by the\r\n            function, instead of being wrapped in the CallInfo.\r\n        \"\"\"\r\n        excinfo = None\r\n        start = timing.time()\r\n        precise_start = timing.perf_counter()\r\n        try:\r\n>           result: Optional[TResult] = func()\r\n\r\n/usr/lib/python3/site-packages/_pytest/runner.py:340: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n/usr/lib/python3/site-packages/_pytest/runner.py:261: in <lambda>\r\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\r\n/usr/lib/python3/site-packages/pluggy/_hooks.py:265: in __call__\r\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\r\n/usr/lib/python3/site-packages/pluggy/_manager.py:80: in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n/usr/lib/python3/site-packages/_pytest/skipping.py:236: in pytest_runtest_setup\r\n    skipped = evaluate_skip_marks(item)\r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n\r\nitem = <Function test_datasheet_yamllint>\r\n\r\n    def evaluate_skip_marks(item: Item) -> Optional[Skip]:\r\n        \"\"\"Evaluate skip and skipif marks on item, returning Skip if triggered.\"\"\"\r\n        for mark in item.iter_markers(name=\"skipif\"):\r\n            if \"condition\" not in mark.kwargs:\r\n                conditions = mark.args\r\n            else:\r\n                conditions = (mark.kwargs[\"condition\"],)\r\n    \r\n            # Unconditional.\r\n            if not conditions:\r\n                reason = mark.kwargs.get(\"reason\", \"\")\r\n                return Skip(reason)\r\n    \r\n            # If any of the conditions are true.\r\n            for condition in conditions:\r\n                result, reason = evaluate_condition(item, mark, condition)\r\n                if result:\r\n                    return Skip(reason)\r\n    \r\n        for mark in item.iter_markers(name=\"skip\"):\r\n            try:\r\n                return Skip(*mark.args, **mark.kwargs)\r\n            except TypeError as e:\r\n>               raise TypeError(str(e) + \" - maybe you meant pytest.mark.skipif?\") from None\r\nE               TypeError: Skip.__init__() got multiple values for argument 'reason' - maybe you meant pytest.mark.skipif?\r\n\r\n/usr/lib/python3/site-packages/_pytest/skipping.py:190: TypeError\r\n=========================== short test summary info ============================\r\nERROR tests/test_code_conventions.py::test_datasheet_yamllint - TypeError: Sk...\r\n================== 637 passed, 258 skipped, 1 error in 43.69s ==================\r\n\r\n```\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1195/timeline","performed_via_github_app":null}},"public":true,"created_at":"2022-03-12T16:40:40Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
